# Generated by Django 5.1.4 on 2025-05-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('motion_duration', models.IntegerField()),
                ('no_motion_duration', models.IntegerField()),
                ('risk', models.IntegerField()),
                ('probability', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
